export default (evaluation, errors) => {
    return {
        "Diversidade e Inclusão": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Ética, Integridade e Compliance": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o engajamento com a integridade da marca e/ou do mercado e sociedade",
            errors: errors?.earnings_engagement,
            name: "earnings_engagement",
            defaultValue: evaluation?.earnings_engagement,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Gestão de Crises": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "f) Resultados obtidos para informação/sensibilização/mobilização dos públicos envolvidos",
            errors: errors?.results_obtained,
            name: "results_obtained",
            defaultValue: evaluation?.results_obtained,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Marca": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Memória Organizacional": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Sustentabilidade Organizacional": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Consumidor/Cliente": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Imprensa e/ou Influenciadores": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "g) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Multipúblicos ": [
            {
                title: "a) Adequação da estratégia ao contexto",
                errors: errors?.strategy_to_context,
                name: "strategy_to_context",
                defaultValue: evaluation?.strategy_to_context,
            },
            {
                title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
                errors: errors?.connection_between_strategy,
                name: "connection_between_strategy",
                defaultValue: evaluation?.connection_between_strategy,
            },
            {
                title: "c) Criatividade e inovação",
                errors: errors?.criativity_and_innovation,
                name: "criativity_and_innovation",
                defaultValue: evaluation?.criativity_and_innovation,
            },
            {
                title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
                errors: errors?.reasonability,
                name: "reasonability",
                defaultValue: evaluation?.reasonability,
            },
            {
                title: "e) Ganhos para o valor da marca",
                errors: errors?.brand_value,
                name: "brand_value",
                defaultValue: evaluation?.brand_value,
            },
            {
                title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
                errors: errors?.case_quality,
                name: "case_quality",
                defaultValue: evaluation?.case_quality,
            }
        ],

        "Público Interno": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Sociedade": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Ganhos para o valor da marca",
            errors: errors?.brand_value,
            name: "brand_value",
            defaultValue: evaluation?.brand_value,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Evento": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas - adequação das peças de comunicação utilizadas ao posicionamento da empresa/organização e ao perfil dos públicos envolvidos",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "e) Qualidade do case – clareza, objetividade e disponibilização de evidência como peças de comunicação, programação, cenografia, canais, clipping, entre outras",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Mídia Audiovisual": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas – adequação da mídia ao posicionamento da empresa/organização e ao perfil dos públicos envolvidos",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Qualidade da mídia – áudio, roteiro, locução, trilha, imagem, fotografia, edição, ritmo/timing",
            errors: errors?.media_quality,
            name: "media_quality",
            defaultValue: evaluation?.media_quality,
        },
        {
            title: "e) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Mídia Digital": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas - adequação das peças de comunicação utilizadas ao posicionamento da empresa/organização e ao perfil dos públicos envolvidos",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Qualidade da mídia – arquitetura, design, funcionalidades, acessibilidade, navegabilidade, conteúdo, interatividade, adequação à marca corporativa.",
            errors: errors?.media_quality,
            name: "media_quality",
            defaultValue: evaluation?.media_quality,
        },
        {
            title: "e) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Mídia Impressa": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas – adequação da mídia ao posicionamento da empresa/organização e ao perfil dos públicos envolvidos",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Qualidade da mídia – projeto gráfico, projeto editorial, linguagem, qualidade de impressão, tiragem e distribuição",
            errors: errors?.media_quality,
            name: "media_quality",
            defaultValue: evaluation?.media_quality,
        },
        {
            title: "e) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],

        "Publicação Especial": [{
            title: "a) Adequação da estratégia ao contexto",
            errors: errors?.strategy_to_context,
            name: "strategy_to_context",
            defaultValue: evaluation?.strategy_to_context,
        },
        {
            title: "b) Conexão entre a estratégia e as ações de comunicação utilizadas – adequação da mídia ao posicionamento da empresa/organização e ao perfil dos públicos envolvidos",
            errors: errors?.connection_between_strategy,
            name: "connection_between_strategy",
            defaultValue: evaluation?.connection_between_strategy,
        },
        {
            title: "c) Criatividade e inovação",
            errors: errors?.criativity_and_innovation,
            name: "criativity_and_innovation",
            defaultValue: evaluation?.criativity_and_innovation,
        },
        {
            title: "d) Qualidade da mídia – projeto gráfico, projeto editorial, linguagem, qualidade de impressão, tiragem e distribuição",
            errors: errors?.media_quality,
            name: "media_quality",
            defaultValue: evaluation?.media_quality,
        },
        {
            title: "e) Razoabilidade – recursos empregados em face dos objetivos e do retorno do investimento",
            errors: errors?.reasonability,
            name: "reasonability",
            defaultValue: evaluation?.reasonability,
        },
        {
            title: "f) Qualidade do case – clareza, objetividade, disponibilização das informações e evidências",
            errors: errors?.case_quality,
            name: "case_quality",
            defaultValue: evaluation?.case_quality,
        }],
    }
}